name: pagate_ia
description: "Págate-IA — Asistente financiero para artesanos y creadores."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0-113.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  equatable: ^2.0.7
  intl: ^0.20.2
  cloud_firestore: ^5.6.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.0
  http: ^1.3.0
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope[wght].ttf
