// File generated by Hermes Agent from google-services.json
// Run `flutterfire configure` on your dev machine to regenerate
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
        apiKey: 'AIzaSyDEQQfn3zJdEJjj8t0C7DdBU8g3Kz_r-vA',
        appId: '1:390581596119:android:6d160588213047dfffa592',
        messagingSenderId: '390581596119',
        projectId: 'pagate-17211',
        storageBucket: 'pagate-17211.firebasestorage.app',
      );
}